Add some drivers

diff --git a/internal/pkg/templater/embedded/templates/main/.github/workflows/ci_cd.yml.tmpl b/internal/pkg/templater/embedded/templates/main/.github/workflows/ci_cd.yml.tmpl
--- a/internal/pkg/templater/embedded/templates/main/.github/workflows/ci_cd.yml.tmpl
+++ b/internal/pkg/templater/embedded/templates/main/.github/workflows/ci_cd.yml.tmpl
@@ -16,22 +16,25 @@ jobs:
       DOMAIN: ${{"{{"}} steps.set_env_main.outputs.DOMAIN {{"}}"}}
       ENV_TYPE: ${{"{{"}} steps.set_env_main.outputs.ENV_TYPE {{"}}"}}
       OC_USER: ${{"{{"}} steps.set_env_main.outputs.OC_USER {{"}}"}}
+      LEN_EXPECTED: ${{"{{"}} steps.vars.outputs.LEN_EXPECTED {{"}}"}}
       OC_PASSWORD: ${{"{{"}} steps.set_env_main.outputs.OC_PASSWORD {{"}}"}}
       SSH_HOST_MATRIX: ${{"{{"}} steps.vars.outputs.SSH_HOST_MATRIX {{"}}"}}
       RELEASE: ${{"{{"}} steps.vers_and_containers.outputs.RELEASE {{"}}"}}
       CONTAINERS: ${{"{{"}} steps.vers_and_containers.outputs.CONTAINERS {{"}}"}}
+      INTERNAL_SUBNET: ${{"{{"}} steps.vars.outputs.INTERNAL_SUBNET {{"}}"}}
       {{- range $_, $a := .Applications }}
         {{ $applicationName := $a.Name | ReplaceDash }}
-        {{- range $_, $t := $a.GetRestTransport }}
+      PORT_PREFIX_{{ $applicationName | ToUpper }}_TRAEFIK: ${{"{{"}} steps.set_env_main.outputs.PORT_PREFIX_{{ $applicationName | ToUpper }}_TRAEFIK {{"}}"}}
+        {{- range $_, $t := $a.GetRestTransport }}{{ if ne $t.GeneratorType "ogen_client" }}
       PORT_PREFIX_{{ $applicationName | ToUpper }}_{{ $t.Name | ToUpper }}: ${{"{{"}} steps.set_env_main.outputs.PORT_PREFIX_{{ $applicationName | ToUpper }}_{{ $t.Name | ToUpper }} {{"}}"}}
-        {{ end }}
+        {{ end }}{{ end }}
       {{ end }}
 
     steps:
       - name: Get branch
         uses: noliran/branch-based-secrets@v1
         with:
-          secrets: ENABLED,DEPLOY_ENVS,DOMAIN,ENV_TYPE,OC_USER,OC_PASSWORD,OC_HOST,{{- range $_, $a := .Applications }}{{ range $_, $t := $a.GetRestTransport }}PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }},{{ end }}{{ end }}SSH_HOST
+          secrets: ENABLED,DOMAIN,ENV_TYPE,OC_USER,OC_PASSWORD,OC_HOST,{{- range $_, $a := .Applications }}PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK,{{ range $_, $t := $a.GetRestTransport }}{{ if ne $t.GeneratorType "ogen_client" }}PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }},{{ end }}{{ end }}{{ end }}SSH_HOST,INTERNAL_SUBNET
 
       - name: Use vars
         id: vars
@@ -48,41 +51,67 @@ jobs:
             exit 1
           fi
 
-          echo "SSH_HOST_MATRIX=${{"{{"}} vars[env.SSH_HOST_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'SSH_HOST_MATRIX=${{"{{"}} vars[env.SSH_HOST_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
 
           if [ -z "${{"{{"}} vars[env.OC_HOST_NAME] {{"}}"}}" ]; then
             echo "Empty OC_HOST"
             exit 2
           fi
-          echo "OC_HOST=${{"{{"}} vars[env.OC_HOST_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'OC_HOST=${{"{{"}} vars[env.OC_HOST_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
+
+          if [ -z "${{"{{"}} vars[env.INTERNAL_SUBNET_NAME] {{"}}"}}" ]; then
+            echo "Empty INTERNAL_SUBNET"
+            exit 2
+          fi
+          echo 'INTERNAL_SUBNET=${{"{{"}} vars[env.INTERNAL_SUBNET_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
 
           echo "skip=0" >> $GITHUB_OUTPUT
 
-          echo "DEPLOY_ENVS="`jq -cn "[range(0; ${{"{{"}} vars[env.DEPLOY_ENVS_NAME] || '1' {{"}}"}})]"` >> $GITHUB_OUTPUT
+          LEN_EXPECTED=$(echo '${{"{{"}} vars[env.ENV_TYPE_NAME] {{"}}"}}' | jq '. | length')
+          if [ -z "$LEN_EXPECTED" ]; then
+            LEN_EXPECTED=1
+          fi
+
+          echo "LEN_EXPECTED=$LEN_EXPECTED" >> $GITHUB_OUTPUT
+          echo DEPLOY_ENVS="`jq -cn "[range(0; $LEN_EXPECTED)]"`" >> $GITHUB_OUTPUT
 
       - name: Check and set vars for instances
         id: set_env_main
         if: steps.vars.outputs.skip == 0
 
         run: |
-          LEN_EXPECTED=${{"{{"}} vars[env.DEPLOY_ENVS_NAME] || '1' {{"}}"}}
+          LEN_EXPECTED=${{"{{"}} steps.vars.outputs.LEN_EXPECTED {{"}}"}}
 
           {{- range $_, $a := .Applications }}
-            {{- range $_, $t := $a.GetRestTransport }}
+            if [ -z "${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK_NAME] {{"}}"}}" ]; then
+              echo "Empty variable ${{"{{"}} env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK_NAME {{"}}"}}"
+              exit 3
+            fi
+
+            LEN=$(echo '${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK_NAME] {{"}}"}}' | jq '. | length')
+
+            if [ "$LEN" != "$LEN_EXPECTED" ]; then
+              echo "Invalid array size ${{"{{"}} env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK_NAME {{"}}"}}: $LEN"
+              exit 4
+            fi
+
+            echo 'PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK=${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash}}_TRAEFIK_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
+
+            {{- range $_, $t := $a.GetRestTransport }}{{ if ne $t.GeneratorType "ogen_client" }}
           if [ -z "${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}_NAME] {{"}}"}}" ]; then
             echo "Empty variable ${{"{{"}} env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}_NAME {{"}}"}}"
             exit 3
           fi
 
-          LEN=$(echo ${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}_NAME] {{"}}"}} | jq '. | length')
+          LEN=$(echo '${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}_NAME] {{"}}"}}' | jq '. | length')
 
           if [ "$LEN" != "$LEN_EXPECTED" ]; then
             echo "Invalid array size ${{"{{"}} env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}_NAME {{"}}"}}: $LEN"
             exit 4
           fi
 
-          echo "PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}=${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash}}_{{ $t.Name | ToUpper }}_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
-            {{ end -}}
+          echo 'PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}=${{"{{"}} vars[env.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash}}_{{ $t.Name | ToUpper }}_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
+            {{ end -}}{{ end -}}
           {{ end -}}
 
           if [ -z "${{"{{"}} vars[env.DOMAIN_NAME] {{"}}"}}" ]; then
@@ -90,50 +119,50 @@ jobs:
             exit 5
           fi
 
-          LEN=$(echo ${{"{{"}} vars[env.DOMAIN_NAME] {{"}}"}} | jq '. | length')
+          LEN=$(echo '${{"{{"}} vars[env.DOMAIN_NAME] {{"}}"}}' | jq '. | length')
 
           if [ "$LEN" != "$LEN_EXPECTED" ]; then
             echo "Invalid array size ${{"{{"}} env.DOMAIN_NAME {{"}}"}}: $LEN"
             exit 6
           fi
 
-          echo "DOMAIN=${{"{{"}} vars[env.DOMAIN_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'DOMAIN=${{"{{"}} vars[env.DOMAIN_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
 
-          LEN=$(echo ${{"{{"}} vars[env.ENV_TYPE_NAME] {{"}}"}} | jq '. | length')
+          LEN=$(echo '${{"{{"}} vars[env.ENV_TYPE_NAME] {{"}}"}}' | jq '. | length')
 
           if [ "$LEN" != "$LEN_EXPECTED" ]; then
             echo "Invalid array size ${{"{{"}} env.ENV_TYPE_NAME {{"}}"}}: $LEN"
             exit 7
           fi
 
-          echo "ENV_TYPE=${{"{{"}} vars[env.ENV_TYPE_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'ENV_TYPE=${{"{{"}} vars[env.ENV_TYPE_NAME] {{"}}"}}' >> $GITHUB_OUTPUT
 
           if [ -z "${{"{{"}} secrets[env.OC_USER_NAME] {{"}}"}}" ]; then
             echo "Empty secrets ${{"{{"}} env.OC_USER_NAME {{"}}"}}"
             exit 8
           fi
 
-          LEN=$(echo ${{"{{"}} secrets[env.OC_USER_NAME] {{"}}"}} | jq '. | length')
+          LEN=$(echo '${{"{{"}} secrets[env.OC_USER_NAME] {{"}}"}}' | jq '. | length')
 
           if [ "$LEN" != "$LEN_EXPECTED" ]; then
             echo "Invalid array size ${{"{{"}} env.OC_USER_NAME {{"}}"}}: $LEN"
             exit 9
           fi
 
-          echo "OC_USER=${{"{{"}} secrets[env.OC_USER_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'OC_USER=${{"{{"}} env.OC_USER_NAME {{"}}"}}' >> $GITHUB_OUTPUT
 
           if [ -z "${{"{{"}} secrets[env.OC_PASSWORD_NAME] {{"}}"}}" ]; then
             echo "Empty secrets ${{"{{"}} env.OC_PASSWORD_NAME {{"}}"}}"
             exit 10
           fi
-          LEN=$(echo ${{"{{"}} secrets[env.OC_PASSWORD_NAME] {{"}}"}} | jq '. | length')
+          LEN=$(echo '${{"{{"}} secrets[env.OC_PASSWORD_NAME] {{"}}"}}' | jq '. | length')
 
           if [ "$LEN" != "$LEN_EXPECTED" ]; then
             echo "Invalid array size ${{"{{"}} env.OC_PASSWORD_NAME {{"}}"}}: $LEN"
             exit 11
           fi
 
-          echo "OC_PASSWORD=${{"{{"}} secrets[env.OC_PASSWORD_NAME] {{"}}"}}" >> $GITHUB_OUTPUT
+          echo 'OC_PASSWORD=${{"{{"}} env.OC_PASSWORD_NAME {{"}}"}}' >> $GITHUB_OUTPUT
 
       - name: Checkout repository
         if: steps.vars.outputs.skip == 0
@@ -178,16 +207,19 @@ jobs:
 
           echo 'DOMAIN="${{"{{"}} fromJson(needs.prepare-env.outputs.DOMAIN)[matrix.envs] {{"}}"}}"' >> $fname
           {{- range $_, $a := .Applications }}
-            {{- range $_, $t := $a.GetRestTransport }}
+          echo 'PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK="${{"{{"}} fromJson(needs.prepare-env.outputs.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_TRAEFIK)[matrix.envs] {{"}}"}}"' >> $fname
+            {{- range $_, $t := $a.GetRestTransport }}{{ if ne $t.GeneratorType "ogen_client" }}
           echo 'PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }}="${{"{{"}} fromJson(needs.prepare-env.outputs.PORT_PREFIX_{{ $a.Name | ToUpper | ReplaceDash }}_{{ $t.Name | ToUpper }})[matrix.envs] {{"}}"}}"' >> $fname
-            {{- end }}
-          {{ end -}}
+            {{- end }}{{- end }}
+          {{- end }}
           echo "ENV_TYPE=$ENV_TYPE" >> $fname
           echo 'OC_HOST="${{"{{"}} needs.prepare-env.outputs.OC_HOST {{"}}"}}"' >> $fname
-          echo 'OC_USER="${{"{{"}} fromJson(needs.prepare-env.outputs.OC_USER)[matrix.envs] {{"}}"}}"' >> $fname
-          echo 'OC_PASSWORD="${{"{{"}} fromJson(needs.prepare-env.outputs.OC_PASSWORD)[matrix.envs] {{"}}"}}"' >> $fname
+          echo 'OC_USER="${{"{{"}} fromJson(secrets[needs.prepare-env.outputs.OC_USER])[matrix.envs] {{"}}"}}"' >> $fname
+          echo 'OC_PASSWORD="${{"{{"}} fromJson(secrets[needs.prepare-env.outputs.OC_PASSWORD])[matrix.envs] {{"}}"}}"' >> $fname
           echo 'APP_VERSION="${{"{{"}} needs.prepare-env.outputs.RELEASE {{"}}"}}"' >> $fname
           echo 'REGISTRY_SERVER=${{"{{"}} secrets.REGISTRY_LOGIN_SERVER {{"}}"}}/${{"{{"}} vars.REGISTRY_CONTAINER {{"}}"}}' >> $fname
+          echo 'INTERNAL_SUBNET=${{"{{"}} needs.prepare-env.outputs.INTERNAL_SUBNET {{"}}"}}' >> $fname
+
 
           # ToDo add file encriptions
           echo "Generated $fname"
@@ -283,6 +315,7 @@ jobs:
           SCRIPT_AFTER_REQUIRED: true
           SCRIPT_AFTER: |
             cd /opt/{{ .ProjectName }}-cd;
+            mv envs/docker-compose-*.yaml ./;
             ./deploy.sh || exit 1;
             echo $RSYNC_STDOUT;
 
